### ISSUE TITLE
This package does not work

### ISSUE THREAD

**Issue by hackingbeauty** [Jabbslad/accounts-github#2]
This package no longer works for me and others (http://stackoverflow.com/questions/18805740/custom-github-login-with-meteor-is-not-working).

How can I test a forked version of this package on my local?  I'd like to submit a patch.

**Comment by AlexFrazer** [comment]
+1 here too. A lot of stuff changed with Meteor upgrading.

**Comment by Jabbslad** [comment]
Hi guys, this was an early attempt at github oauth2 prior to Meteor building in their own support. Their package is probably the one to use: https://github.com/meteor/meteor/tree/devel/packages/accounts-github
