### ISSUE TITLE
How to get profile name when authenticating users?

### ISSUE THREAD

**Issue by brylie** [Jabbslad/accounts-github#5]
When authenticating via Github, what information can we access via the `user.services.github`object? E.g. first name, full name, email, etc.

**Comment by brylie** [comment]
I notice the additional `extra` field in [github_server.js](https://github.com/Jabbslad/accounts-github/blob/master/github_server.js#L20). How can we access `extra: {profile: {name: identity.name}}` when authenticating a user, so that we can add this information to our database?

**Comment by Jabbslad** [comment]
@brylie please refer to https://github.com/Jabbslad/accounts-github/issues/2#issuecomment-90842652 . Hope that helps
